### ISSUE TITLE
rapid 2020 - progress tracking

### ISSUE THREAD

**Issue by liquid600pgm** [liquid600pgm/rapid#23]
Since rapid 2020 has now been merged to master, the checklist from #22 has been moved here:

- [ ] rapid/graphics
  - [ ] context.nim
    - [x] basic shapes
    - [x] polylines
    - [x] sprites
    - [x] text
    - [ ] extra shapes:
      - [ ] optimized arc outlines - right now (`ac7187f`) they use slow polyline rendering
      - [ ] rounded rectangles - fills and outlines
  - [x] postprocess.nim
- [ ] ~~rapid/ecs~~ will not be finished for 2020.1, rather separated into its own issue and developed there
  - [x] DSL for systems
  - [x] DSL for constructing the ECS world
    - [x] types: `@entity`, `@world`, `@entityHas`
    - [x] procs/iterators:
      - world creation: ~~`init@world`~~ won't be necessary, as just creating a zeroed `World` variable works fine,
      - [x] obtaining components: `component`, `mcomponent`,
      - [x] managing components: `addComponent`, `delComponent`, `hasComponent`,
      - [x] entity manager: `new@entity`, `del@entity`, iterator `entities`
  - [ ] common components
    - ~~all ECS components must be named using the pattern `Comp<name>`~~ stupid idea, components can be named however you want
    - [x] components/basic.nim – Position, Size, Color, etc.
    - [x] components/physics.nim – PhysicsBody (velocity, acceleration), Gravity, TerminalVelocity, etc.
    - [ ] components/graphics.nim – Sprite, shapes (?), etc.
    - [ ] components/tilemap.nim – Tilemap[T] (will need generic component and system support), TilemapPhysics
  - [ ] systems
    - all systems export their required components, so ultimately the user doesn't need to import any components
    - [ ] draw.nim – drawRect, drawSprite, etc.
    - [ ] physics.nim – physics, gravity, velocityCap, etc.
    - [ ] tilemap.nim – tilemapCollision
- [x] rapid/ec.nim - simpler object-oriented alternative to rapid/ecs based on the [component pattern](https://gameprogrammingpatterns.com/component.html)
- [x] rapid/physics - lightweight physics and collision-related stuff
- [ ] rapid/audio
  - will probably have the same (or similar) API but without the `R` prefixes
- [x] rapid/game.nim - fixed timestep game loop macro
- [ ] rapid/ui - replacement for [rdgui](https://github.com/liquid600pgm/rdgui), [fidget](https://github.com/treeform/fidget)-like API
